### ISSUE TITLE
error TS2345: Argument of type 'TransactionSql<{}>' is not assignable to parameter of type 'Sql<{}>'

### ISSUE THREAD

**Issue by maarre** [porsager/postgres#1163]
This is typescript.

> src/importdog.ts(58,92): error TS2345: Argument of type 'TransactionSql<{}>' is not assignable to parameter of type 'Sql<{}>'.
>   Type 'TransactionSql<{}>' is missing the following properties from type 'Sql<{}>': CLOSE, END, PostgresError, options, and 7 more.

This works in postgres 3.4.7. It didn't work in 3.4.8. It doesn't work in 3.4.9. 
```
export const dog_subsidy = postgres({
            user: 'dog_subsidy',
            password: process.env.DOG_SUBSIDY_PASSWORD,
            host: 'localhost',
            port: 5432,
            database: 'dog_subsidy',
            max: os.cpus().length,
            debug: postgres_logger
        })
```

```
export async function sp_personsimm_create_v1(params: IfsPersonParamsSpPersonsimmCreateV1, breadcrumb: string, db = dog_subsidy): Promise<number |UserError> {
```

```
await dog_subsidy.begin(async conn => {
                const breeder = dog.breeder
                const breeder_imm =
                    new PersonParamsSpPersonsimmCreateV1(breeder.social_security_number.toString(), undefined)
                const breederimm_pk = await sp_personsimm_create_v1(breeder_imm, uuidv4(), conn)
```
The error is the last parameter in call to await sp_personsimm_create_v1(breeder_imm, uuidv4(), conn)

```
$ grep -e postgres -e typescript -e 'tsup":' package.json
    "postgres": "3.4.9",
    "tsup": "8.5.1",
    "typescript": "5.9.3",
```

```
$ node --version
v22.16.0

```

**Comment by porsager** [comment]
Probably caused by this change https://github.com/porsager/postgres/pull/1144

**Comment by sep2** [comment]
I don't think this is an issue from #1144.

You are passing `trx` object from `.begin(trx)` to a function expecting `Sql`. They are actually different runtime objects. As indicated in https://github.com/porsager/postgres/pull/1144#issuecomment-3718662189 `trx` has fields `sql` does not  have, and vice versa.

#1144 catches the bug in your code, not the cause of it.

Basically if you want a generic function that can accept both `trx` and `sql`, you should not let typescript default it to the type `Sql`, but to annotate its parameter type as `SqlOrTrx` like below:

```typescript
import type { Sql as RawSql, TransactionSql } from 'postgres'

export type SqlRecordType = Record<string, unknown>

export type Trx = TransactionSql<SqlRecordType>

export type Sql = RawSql<SqlRecordType>

export type SqlOrTrx = Sql | Trx

export async function beginTransactionOrSavepoint<T>(
    handle: SqlOrTrx,
    callback: (trx: Trx) => Promise<T>
): Promise<T> {
    if ('savepoint' in handle) {
        return (await handle.savepoint(async (trx) => await callback(trx))) as Promise<T>
    } else if ('begin' in handle) {
        return (await handle.begin(async (trx) => await callback(trx))) as Promise<T>
    } else {
        throw new Error('unknown transaction handler')
    }
}

```

**Comment by AntonOfTheWoods** [comment]
@maarre can you provide a proper repro in a file, so we can not waste time hoping to put it together like you did?

**Comment by maarre** [comment]
@AntonOfTheWoods, I will try to make the whole thing open source. It will take som e time though.

**Comment by maarre** [comment]
@sep2 are you using semantic versioning? If so this is just a bugfix version and should not break things.

**Comment by AntonOfTheWoods** [comment]
> @sep2 are you using semantic versioning? If so this is just a bugfix version and should not break things.

This is typescript... So it's just type checking. While I personally would get angry if someone made this argument with me... :-), it's not "broken" in terms of database access. Inconvenient, sure, but not "broken". And in any case, it looks like the fix helped many of us, just not everyone. Maybe another PR?

**Comment by sep2** [comment]
> [@sep2](https://github.com/sep2) are you using semantic versioning? If so this is just a bugfix version and should not break things.

If you are using TypeScript you have to follow type rules, otherwise It's better to use pure JavaScript. This PR merely fix the type bug introduced in 3.4.8. It only breaks invalid type code as intended, which I don't think has anything to do with semantic versioning.

**Comment by maarre** [comment]
> [@maarre](https://github.com/maarre) can you provide a proper repro in a file, so we can not waste time hoping to put it together like you did?

I have made example code. It is now in review for use outside my company.

**Comment by maarre** [comment]
[1163.zip](https://github.com/user-attachments/files/26600198/1163.zip)

I have simplified my application. But still there are lots of dead code. It runs though.

Unpack and then run make.sh

There will be lots of errors/warnings/retries because of clashes in the database.

Then update package.json to 3.4.9. And build. This is what I get:

```
$ git diff
diff --git a/buggar/1163/package.json b/buggar/1163/package.json
index 25746fb..2570e17 100644
--- a/buggar/1163/package.json
+++ b/buggar/1163/package.json
@@ -1,7 +1,7 @@
 {
   "dependencies": {
     "commander": "14.0.3",
-    "postgres": "3.4.7",
+    "postgres": "3.4.9",
     "uuid": "13.0.0",
     "loglayer": "9.1.0",
     "prexit": "2.3.0",
```

```
$ npm run build

> d7-dog_subsidy-wrappers@1.0.1775713576172+alpha build
> tsc && tsup

src/importdog.ts(52,107): error TS2345: Argument of type 'TransactionSql<{}>' is not assignable to parameter of type 'Sql<{}>'.
  Type 'TransactionSql<{}>' is missing the following properties from type 'Sql<{}>': CLOSE, END, PostgresError, options, and 7 more.
src/importdog.ts(59,103): error TS2345: Argument of type 'TransactionSql<{}>' is not assignable to parameter of type 'Sql<{}>'.
  Type 'TransactionSql<{}>' is missing the following properties from type 'Sql<{}>': CLOSE, END, PostgresError, options, and 7 more.
src/importdog.ts(67,103): error TS2345: Argument of type 'TransactionSql<{}>' is not assignable to parameter of type 'Sql<{}>'.
  Type 'TransactionSql<{}>' is missing the following properties from type 'Sql<{}>': CLOSE, END, PostgresError, options, and 7 more.
src/importdog.ts(76,109): error TS2345: Argument of type 'TransactionSql<{}>' is not assignable to parameter of type 'Sql<{}>'.
  Type 'TransactionSql<{}>' is missing the following properties from type 'Sql<{}>': CLOSE, END, PostgresError, options, and 7 more.
```

**Comment by tonytamps** [comment]
> [1163.zip](https://github.com/user-attachments/files/26600198/1163.zip)

@maarre - sharing a zip file is going to discourage most from helping because downloading a zip off the internet is a good way to get infected with something. The good news is that this is github and you can create unlimited public repositories which you can allow people to see without the security risk. 

Would you please put the replication into a repository or branch for people to read?

**Comment by maarre** [comment]
Thanks @tonytamps . I will do that.

**Comment by maarre** [comment]
> Thanks [@tonytamps](https://github.com/tonytamps) . I will do that.

https://github.com/maarre/porsager.postgres.1163

**Comment by maarre** [comment]
> > Thanks [@tonytamps](https://github.com/tonytamps) . I will do that.
> 
> https://github.com/maarre/porsager.postgres.1163


> [@maarre](https://github.com/maarre) can you provide a proper repro in a file, so we can not waste time hoping to put it together like you did?

**Comment by AntonOfTheWoods** [comment]
> > [@maarre](https://github.com/maarre) can you provide a proper repro in a file, so we can not waste time hoping to put it together like you did?

@maarre  I (maybe not obviously?) meant in a github repo or similar - I guess I can understand the confusion. zip isn't wrong per se I guess... just maybe what we did back in the early 2000s before github existed :-).

**Comment by maarre** [comment]
This is where I am calling from: https://github.com/maarre/porsager.postgres.1163/blob/main/src/importdog.ts#L52

This is the declaration of the called function: https://github.com/maarre/porsager.postgres.1163/blob/main/src/personwrapper.ts#L349

Here is the default parameter declaration: https://github.com/maarre/porsager.postgres.1163/blob/main/src/helpers.ts#L19
